version: '3'

services:
  server:
    container_name: server-api
    image: costadiogo30/backend
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
